/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShowcaseRouteImport } from './routes/_showcase'
import { Route as HooksRouteImport } from './routes/_hooks'
import { Route as ShowcaseIndexRouteImport } from './routes/_showcase/index'
import { Route as HooksWagmiRouteImport } from './routes/_hooks/wagmi'
import { Route as HooksSolanaRouteImport } from './routes/_hooks/solana'
import { Route as HooksProviderRouteImport } from './routes/_hooks/provider'
import { Route as HooksAdapterRouteImport } from './routes/_hooks/adapter'
import { Route as ShowcaseShowcaseAuthRouteImport } from './routes/_showcase/showcase/auth'
import { Route as HooksWalletUseWalletsRouteImport } from './routes/_hooks/wallet/useWallets'
import { Route as HooksWalletUseWalletAssetsRouteImport } from './routes/_hooks/wallet/useWalletAssets'
import { Route as HooksWalletUseSolanaEmbeddedWalletRouteImport } from './routes/_hooks/wallet/useSolanaEmbeddedWallet'
import { Route as HooksWagmiUseSwitchChainRouteImport } from './routes/_hooks/wagmi/useSwitchChain'
import { Route as HooksWagmiUseDisconnectRouteImport } from './routes/_hooks/wagmi/useDisconnect'
import { Route as HooksWagmiUseBalanceRouteImport } from './routes/_hooks/wagmi/useBalance'
import { Route as HooksWagmiUseAccountRouteImport } from './routes/_hooks/wagmi/useAccount'
import { Route as HooksUtilsUseUIRouteImport } from './routes/_hooks/utils/useUI'
import { Route as HooksSolanaUseSwitchClusterRouteImport } from './routes/_hooks/solana/useSwitchCluster'
import { Route as HooksSolanaUseSolanaBalanceRouteImport } from './routes/_hooks/solana/useSolanaBalance'
import { Route as HooksSolanaUseSolanaAccountRouteImport } from './routes/_hooks/solana/useSolanaAccount'
import { Route as HooksSolanaUseDisconnectRouteImport } from './routes/_hooks/solana/useDisconnect'
import { Route as HooksAuthUseWalletAuthRouteImport } from './routes/_hooks/auth/useWalletAuth'
import { Route as HooksAuthUseUserRouteImport } from './routes/_hooks/auth/useUser'
import { Route as HooksAuthUseSignOutRouteImport } from './routes/_hooks/auth/useSignOut'
import { Route as HooksAuthUseOauthRouteImport } from './routes/_hooks/auth/useOauth'
import { Route as HooksAuthUseGuestAuthRouteImport } from './routes/_hooks/auth/useGuestAuth'
import { Route as HooksAuthUseEmailAuthRouteImport } from './routes/_hooks/auth/useEmailAuth'
import { Route as HooksAuthUseAuthCallbackRouteImport } from './routes/_hooks/auth/useAuthCallback'
import { Route as HooksAdapterUseSwitchChainRouteImport } from './routes/_hooks/adapter/useSwitchChain'
import { Route as HooksAdapterUseDisconnectRouteImport } from './routes/_hooks/adapter/useDisconnect'
import { Route as HooksAdapterUseBalanceRouteImport } from './routes/_hooks/adapter/useBalance'
import { Route as HooksAdapterUseAccountRouteImport } from './routes/_hooks/adapter/useAccount'
import { Route as ShowcaseShowcaseAuthIndexRouteImport } from './routes/_showcase/showcase/auth/index'
import { Route as ShowcaseShowcaseAuthSignupRouteImport } from './routes/_showcase/showcase/auth/signup'
import { Route as ShowcaseShowcaseAuthPasswordCallbackRouteImport } from './routes/_showcase/showcase/auth/password-callback'
import { Route as ShowcaseShowcaseAuthLoginRouteImport } from './routes/_showcase/showcase/auth/login'
import { Route as ShowcaseShowcaseAuthForgotPasswordRouteImport } from './routes/_showcase/showcase/auth/forgot-password'
import { Route as ShowcaseShowcaseAuthConnectWalletRouteImport } from './routes/_showcase/showcase/auth/connect-wallet'
import { Route as ShowcaseShowcaseAuthCallbackRouteImport } from './routes/_showcase/showcase/auth/callback'

const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/_showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksRoute = HooksRouteImport.update({
  id: '/_hooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseIndexRoute = ShowcaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShowcaseRoute,
} as any)
const HooksWagmiRoute = HooksWagmiRouteImport.update({
  id: '/wagmi',
  path: '/wagmi',
  getParentRoute: () => HooksRoute,
} as any)
const HooksSolanaRoute = HooksSolanaRouteImport.update({
  id: '/solana',
  path: '/solana',
  getParentRoute: () => HooksRoute,
} as any)
const HooksProviderRoute = HooksProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => HooksRoute,
} as any)
const HooksAdapterRoute = HooksAdapterRouteImport.update({
  id: '/adapter',
  path: '/adapter',
  getParentRoute: () => HooksRoute,
} as any)
const ShowcaseShowcaseAuthRoute = ShowcaseShowcaseAuthRouteImport.update({
  id: '/showcase/auth',
  path: '/showcase/auth',
  getParentRoute: () => ShowcaseRoute,
} as any)
const HooksWalletUseWalletsRoute = HooksWalletUseWalletsRouteImport.update({
  id: '/wallet/useWallets',
  path: '/wallet/useWallets',
  getParentRoute: () => HooksRoute,
} as any)
const HooksWalletUseWalletAssetsRoute =
  HooksWalletUseWalletAssetsRouteImport.update({
    id: '/wallet/useWalletAssets',
    path: '/wallet/useWalletAssets',
    getParentRoute: () => HooksRoute,
  } as any)
const HooksWalletUseSolanaEmbeddedWalletRoute =
  HooksWalletUseSolanaEmbeddedWalletRouteImport.update({
    id: '/wallet/useSolanaEmbeddedWallet',
    path: '/wallet/useSolanaEmbeddedWallet',
    getParentRoute: () => HooksRoute,
  } as any)
const HooksWagmiUseSwitchChainRoute =
  HooksWagmiUseSwitchChainRouteImport.update({
    id: '/useSwitchChain',
    path: '/useSwitchChain',
    getParentRoute: () => HooksWagmiRoute,
  } as any)
const HooksWagmiUseDisconnectRoute = HooksWagmiUseDisconnectRouteImport.update({
  id: '/useDisconnect',
  path: '/useDisconnect',
  getParentRoute: () => HooksWagmiRoute,
} as any)
const HooksWagmiUseBalanceRoute = HooksWagmiUseBalanceRouteImport.update({
  id: '/useBalance',
  path: '/useBalance',
  getParentRoute: () => HooksWagmiRoute,
} as any)
const HooksWagmiUseAccountRoute = HooksWagmiUseAccountRouteImport.update({
  id: '/useAccount',
  path: '/useAccount',
  getParentRoute: () => HooksWagmiRoute,
} as any)
const HooksUtilsUseUIRoute = HooksUtilsUseUIRouteImport.update({
  id: '/utils/useUI',
  path: '/utils/useUI',
  getParentRoute: () => HooksRoute,
} as any)
const HooksSolanaUseSwitchClusterRoute =
  HooksSolanaUseSwitchClusterRouteImport.update({
    id: '/useSwitchCluster',
    path: '/useSwitchCluster',
    getParentRoute: () => HooksSolanaRoute,
  } as any)
const HooksSolanaUseSolanaBalanceRoute =
  HooksSolanaUseSolanaBalanceRouteImport.update({
    id: '/useSolanaBalance',
    path: '/useSolanaBalance',
    getParentRoute: () => HooksSolanaRoute,
  } as any)
const HooksSolanaUseSolanaAccountRoute =
  HooksSolanaUseSolanaAccountRouteImport.update({
    id: '/useSolanaAccount',
    path: '/useSolanaAccount',
    getParentRoute: () => HooksSolanaRoute,
  } as any)
const HooksSolanaUseDisconnectRoute =
  HooksSolanaUseDisconnectRouteImport.update({
    id: '/useDisconnect',
    path: '/useDisconnect',
    getParentRoute: () => HooksSolanaRoute,
  } as any)
const HooksAuthUseWalletAuthRoute = HooksAuthUseWalletAuthRouteImport.update({
  id: '/auth/useWalletAuth',
  path: '/auth/useWalletAuth',
  getParentRoute: () => HooksRoute,
} as any)
const HooksAuthUseUserRoute = HooksAuthUseUserRouteImport.update({
  id: '/auth/useUser',
  path: '/auth/useUser',
  getParentRoute: () => HooksRoute,
} as any)
const HooksAuthUseSignOutRoute = HooksAuthUseSignOutRouteImport.update({
  id: '/auth/useSignOut',
  path: '/auth/useSignOut',
  getParentRoute: () => HooksRoute,
} as any)
const HooksAuthUseOauthRoute = HooksAuthUseOauthRouteImport.update({
  id: '/auth/useOauth',
  path: '/auth/useOauth',
  getParentRoute: () => HooksRoute,
} as any)
const HooksAuthUseGuestAuthRoute = HooksAuthUseGuestAuthRouteImport.update({
  id: '/auth/useGuestAuth',
  path: '/auth/useGuestAuth',
  getParentRoute: () => HooksRoute,
} as any)
const HooksAuthUseEmailAuthRoute = HooksAuthUseEmailAuthRouteImport.update({
  id: '/auth/useEmailAuth',
  path: '/auth/useEmailAuth',
  getParentRoute: () => HooksRoute,
} as any)
const HooksAuthUseAuthCallbackRoute =
  HooksAuthUseAuthCallbackRouteImport.update({
    id: '/auth/useAuthCallback',
    path: '/auth/useAuthCallback',
    getParentRoute: () => HooksRoute,
  } as any)
const HooksAdapterUseSwitchChainRoute =
  HooksAdapterUseSwitchChainRouteImport.update({
    id: '/useSwitchChain',
    path: '/useSwitchChain',
    getParentRoute: () => HooksAdapterRoute,
  } as any)
const HooksAdapterUseDisconnectRoute =
  HooksAdapterUseDisconnectRouteImport.update({
    id: '/useDisconnect',
    path: '/useDisconnect',
    getParentRoute: () => HooksAdapterRoute,
  } as any)
const HooksAdapterUseBalanceRoute = HooksAdapterUseBalanceRouteImport.update({
  id: '/useBalance',
  path: '/useBalance',
  getParentRoute: () => HooksAdapterRoute,
} as any)
const HooksAdapterUseAccountRoute = HooksAdapterUseAccountRouteImport.update({
  id: '/useAccount',
  path: '/useAccount',
  getParentRoute: () => HooksAdapterRoute,
} as any)
const ShowcaseShowcaseAuthIndexRoute =
  ShowcaseShowcaseAuthIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ShowcaseShowcaseAuthRoute,
  } as any)
const ShowcaseShowcaseAuthSignupRoute =
  ShowcaseShowcaseAuthSignupRouteImport.update({
    id: '/signup',
    path: '/signup',
    getParentRoute: () => ShowcaseShowcaseAuthRoute,
  } as any)
const ShowcaseShowcaseAuthPasswordCallbackRoute =
  ShowcaseShowcaseAuthPasswordCallbackRouteImport.update({
    id: '/password-callback',
    path: '/password-callback',
    getParentRoute: () => ShowcaseShowcaseAuthRoute,
  } as any)
const ShowcaseShowcaseAuthLoginRoute =
  ShowcaseShowcaseAuthLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => ShowcaseShowcaseAuthRoute,
  } as any)
const ShowcaseShowcaseAuthForgotPasswordRoute =
  ShowcaseShowcaseAuthForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => ShowcaseShowcaseAuthRoute,
  } as any)
const ShowcaseShowcaseAuthConnectWalletRoute =
  ShowcaseShowcaseAuthConnectWalletRouteImport.update({
    id: '/connect-wallet',
    path: '/connect-wallet',
    getParentRoute: () => ShowcaseShowcaseAuthRoute,
  } as any)
const ShowcaseShowcaseAuthCallbackRoute =
  ShowcaseShowcaseAuthCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => ShowcaseShowcaseAuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShowcaseIndexRoute
  '/adapter': typeof HooksAdapterRouteWithChildren
  '/provider': typeof HooksProviderRoute
  '/solana': typeof HooksSolanaRouteWithChildren
  '/wagmi': typeof HooksWagmiRouteWithChildren
  '/adapter/useAccount': typeof HooksAdapterUseAccountRoute
  '/adapter/useBalance': typeof HooksAdapterUseBalanceRoute
  '/adapter/useDisconnect': typeof HooksAdapterUseDisconnectRoute
  '/adapter/useSwitchChain': typeof HooksAdapterUseSwitchChainRoute
  '/auth/useAuthCallback': typeof HooksAuthUseAuthCallbackRoute
  '/auth/useEmailAuth': typeof HooksAuthUseEmailAuthRoute
  '/auth/useGuestAuth': typeof HooksAuthUseGuestAuthRoute
  '/auth/useOauth': typeof HooksAuthUseOauthRoute
  '/auth/useSignOut': typeof HooksAuthUseSignOutRoute
  '/auth/useUser': typeof HooksAuthUseUserRoute
  '/auth/useWalletAuth': typeof HooksAuthUseWalletAuthRoute
  '/solana/useDisconnect': typeof HooksSolanaUseDisconnectRoute
  '/solana/useSolanaAccount': typeof HooksSolanaUseSolanaAccountRoute
  '/solana/useSolanaBalance': typeof HooksSolanaUseSolanaBalanceRoute
  '/solana/useSwitchCluster': typeof HooksSolanaUseSwitchClusterRoute
  '/utils/useUI': typeof HooksUtilsUseUIRoute
  '/wagmi/useAccount': typeof HooksWagmiUseAccountRoute
  '/wagmi/useBalance': typeof HooksWagmiUseBalanceRoute
  '/wagmi/useDisconnect': typeof HooksWagmiUseDisconnectRoute
  '/wagmi/useSwitchChain': typeof HooksWagmiUseSwitchChainRoute
  '/wallet/useSolanaEmbeddedWallet': typeof HooksWalletUseSolanaEmbeddedWalletRoute
  '/wallet/useWalletAssets': typeof HooksWalletUseWalletAssetsRoute
  '/wallet/useWallets': typeof HooksWalletUseWalletsRoute
  '/showcase/auth': typeof ShowcaseShowcaseAuthRouteWithChildren
  '/showcase/auth/callback': typeof ShowcaseShowcaseAuthCallbackRoute
  '/showcase/auth/connect-wallet': typeof ShowcaseShowcaseAuthConnectWalletRoute
  '/showcase/auth/forgot-password': typeof ShowcaseShowcaseAuthForgotPasswordRoute
  '/showcase/auth/login': typeof ShowcaseShowcaseAuthLoginRoute
  '/showcase/auth/password-callback': typeof ShowcaseShowcaseAuthPasswordCallbackRoute
  '/showcase/auth/signup': typeof ShowcaseShowcaseAuthSignupRoute
  '/showcase/auth/': typeof ShowcaseShowcaseAuthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ShowcaseIndexRoute
  '/adapter': typeof HooksAdapterRouteWithChildren
  '/provider': typeof HooksProviderRoute
  '/solana': typeof HooksSolanaRouteWithChildren
  '/wagmi': typeof HooksWagmiRouteWithChildren
  '/adapter/useAccount': typeof HooksAdapterUseAccountRoute
  '/adapter/useBalance': typeof HooksAdapterUseBalanceRoute
  '/adapter/useDisconnect': typeof HooksAdapterUseDisconnectRoute
  '/adapter/useSwitchChain': typeof HooksAdapterUseSwitchChainRoute
  '/auth/useAuthCallback': typeof HooksAuthUseAuthCallbackRoute
  '/auth/useEmailAuth': typeof HooksAuthUseEmailAuthRoute
  '/auth/useGuestAuth': typeof HooksAuthUseGuestAuthRoute
  '/auth/useOauth': typeof HooksAuthUseOauthRoute
  '/auth/useSignOut': typeof HooksAuthUseSignOutRoute
  '/auth/useUser': typeof HooksAuthUseUserRoute
  '/auth/useWalletAuth': typeof HooksAuthUseWalletAuthRoute
  '/solana/useDisconnect': typeof HooksSolanaUseDisconnectRoute
  '/solana/useSolanaAccount': typeof HooksSolanaUseSolanaAccountRoute
  '/solana/useSolanaBalance': typeof HooksSolanaUseSolanaBalanceRoute
  '/solana/useSwitchCluster': typeof HooksSolanaUseSwitchClusterRoute
  '/utils/useUI': typeof HooksUtilsUseUIRoute
  '/wagmi/useAccount': typeof HooksWagmiUseAccountRoute
  '/wagmi/useBalance': typeof HooksWagmiUseBalanceRoute
  '/wagmi/useDisconnect': typeof HooksWagmiUseDisconnectRoute
  '/wagmi/useSwitchChain': typeof HooksWagmiUseSwitchChainRoute
  '/wallet/useSolanaEmbeddedWallet': typeof HooksWalletUseSolanaEmbeddedWalletRoute
  '/wallet/useWalletAssets': typeof HooksWalletUseWalletAssetsRoute
  '/wallet/useWallets': typeof HooksWalletUseWalletsRoute
  '/showcase/auth/callback': typeof ShowcaseShowcaseAuthCallbackRoute
  '/showcase/auth/connect-wallet': typeof ShowcaseShowcaseAuthConnectWalletRoute
  '/showcase/auth/forgot-password': typeof ShowcaseShowcaseAuthForgotPasswordRoute
  '/showcase/auth/login': typeof ShowcaseShowcaseAuthLoginRoute
  '/showcase/auth/password-callback': typeof ShowcaseShowcaseAuthPasswordCallbackRoute
  '/showcase/auth/signup': typeof ShowcaseShowcaseAuthSignupRoute
  '/showcase/auth': typeof ShowcaseShowcaseAuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_hooks': typeof HooksRouteWithChildren
  '/_showcase': typeof ShowcaseRouteWithChildren
  '/_hooks/adapter': typeof HooksAdapterRouteWithChildren
  '/_hooks/provider': typeof HooksProviderRoute
  '/_hooks/solana': typeof HooksSolanaRouteWithChildren
  '/_hooks/wagmi': typeof HooksWagmiRouteWithChildren
  '/_showcase/': typeof ShowcaseIndexRoute
  '/_hooks/adapter/useAccount': typeof HooksAdapterUseAccountRoute
  '/_hooks/adapter/useBalance': typeof HooksAdapterUseBalanceRoute
  '/_hooks/adapter/useDisconnect': typeof HooksAdapterUseDisconnectRoute
  '/_hooks/adapter/useSwitchChain': typeof HooksAdapterUseSwitchChainRoute
  '/_hooks/auth/useAuthCallback': typeof HooksAuthUseAuthCallbackRoute
  '/_hooks/auth/useEmailAuth': typeof HooksAuthUseEmailAuthRoute
  '/_hooks/auth/useGuestAuth': typeof HooksAuthUseGuestAuthRoute
  '/_hooks/auth/useOauth': typeof HooksAuthUseOauthRoute
  '/_hooks/auth/useSignOut': typeof HooksAuthUseSignOutRoute
  '/_hooks/auth/useUser': typeof HooksAuthUseUserRoute
  '/_hooks/auth/useWalletAuth': typeof HooksAuthUseWalletAuthRoute
  '/_hooks/solana/useDisconnect': typeof HooksSolanaUseDisconnectRoute
  '/_hooks/solana/useSolanaAccount': typeof HooksSolanaUseSolanaAccountRoute
  '/_hooks/solana/useSolanaBalance': typeof HooksSolanaUseSolanaBalanceRoute
  '/_hooks/solana/useSwitchCluster': typeof HooksSolanaUseSwitchClusterRoute
  '/_hooks/utils/useUI': typeof HooksUtilsUseUIRoute
  '/_hooks/wagmi/useAccount': typeof HooksWagmiUseAccountRoute
  '/_hooks/wagmi/useBalance': typeof HooksWagmiUseBalanceRoute
  '/_hooks/wagmi/useDisconnect': typeof HooksWagmiUseDisconnectRoute
  '/_hooks/wagmi/useSwitchChain': typeof HooksWagmiUseSwitchChainRoute
  '/_hooks/wallet/useSolanaEmbeddedWallet': typeof HooksWalletUseSolanaEmbeddedWalletRoute
  '/_hooks/wallet/useWalletAssets': typeof HooksWalletUseWalletAssetsRoute
  '/_hooks/wallet/useWallets': typeof HooksWalletUseWalletsRoute
  '/_showcase/showcase/auth': typeof ShowcaseShowcaseAuthRouteWithChildren
  '/_showcase/showcase/auth/callback': typeof ShowcaseShowcaseAuthCallbackRoute
  '/_showcase/showcase/auth/connect-wallet': typeof ShowcaseShowcaseAuthConnectWalletRoute
  '/_showcase/showcase/auth/forgot-password': typeof ShowcaseShowcaseAuthForgotPasswordRoute
  '/_showcase/showcase/auth/login': typeof ShowcaseShowcaseAuthLoginRoute
  '/_showcase/showcase/auth/password-callback': typeof ShowcaseShowcaseAuthPasswordCallbackRoute
  '/_showcase/showcase/auth/signup': typeof ShowcaseShowcaseAuthSignupRoute
  '/_showcase/showcase/auth/': typeof ShowcaseShowcaseAuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adapter'
    | '/provider'
    | '/solana'
    | '/wagmi'
    | '/adapter/useAccount'
    | '/adapter/useBalance'
    | '/adapter/useDisconnect'
    | '/adapter/useSwitchChain'
    | '/auth/useAuthCallback'
    | '/auth/useEmailAuth'
    | '/auth/useGuestAuth'
    | '/auth/useOauth'
    | '/auth/useSignOut'
    | '/auth/useUser'
    | '/auth/useWalletAuth'
    | '/solana/useDisconnect'
    | '/solana/useSolanaAccount'
    | '/solana/useSolanaBalance'
    | '/solana/useSwitchCluster'
    | '/utils/useUI'
    | '/wagmi/useAccount'
    | '/wagmi/useBalance'
    | '/wagmi/useDisconnect'
    | '/wagmi/useSwitchChain'
    | '/wallet/useSolanaEmbeddedWallet'
    | '/wallet/useWalletAssets'
    | '/wallet/useWallets'
    | '/showcase/auth'
    | '/showcase/auth/callback'
    | '/showcase/auth/connect-wallet'
    | '/showcase/auth/forgot-password'
    | '/showcase/auth/login'
    | '/showcase/auth/password-callback'
    | '/showcase/auth/signup'
    | '/showcase/auth/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adapter'
    | '/provider'
    | '/solana'
    | '/wagmi'
    | '/adapter/useAccount'
    | '/adapter/useBalance'
    | '/adapter/useDisconnect'
    | '/adapter/useSwitchChain'
    | '/auth/useAuthCallback'
    | '/auth/useEmailAuth'
    | '/auth/useGuestAuth'
    | '/auth/useOauth'
    | '/auth/useSignOut'
    | '/auth/useUser'
    | '/auth/useWalletAuth'
    | '/solana/useDisconnect'
    | '/solana/useSolanaAccount'
    | '/solana/useSolanaBalance'
    | '/solana/useSwitchCluster'
    | '/utils/useUI'
    | '/wagmi/useAccount'
    | '/wagmi/useBalance'
    | '/wagmi/useDisconnect'
    | '/wagmi/useSwitchChain'
    | '/wallet/useSolanaEmbeddedWallet'
    | '/wallet/useWalletAssets'
    | '/wallet/useWallets'
    | '/showcase/auth/callback'
    | '/showcase/auth/connect-wallet'
    | '/showcase/auth/forgot-password'
    | '/showcase/auth/login'
    | '/showcase/auth/password-callback'
    | '/showcase/auth/signup'
    | '/showcase/auth'
  id:
    | '__root__'
    | '/_hooks'
    | '/_showcase'
    | '/_hooks/adapter'
    | '/_hooks/provider'
    | '/_hooks/solana'
    | '/_hooks/wagmi'
    | '/_showcase/'
    | '/_hooks/adapter/useAccount'
    | '/_hooks/adapter/useBalance'
    | '/_hooks/adapter/useDisconnect'
    | '/_hooks/adapter/useSwitchChain'
    | '/_hooks/auth/useAuthCallback'
    | '/_hooks/auth/useEmailAuth'
    | '/_hooks/auth/useGuestAuth'
    | '/_hooks/auth/useOauth'
    | '/_hooks/auth/useSignOut'
    | '/_hooks/auth/useUser'
    | '/_hooks/auth/useWalletAuth'
    | '/_hooks/solana/useDisconnect'
    | '/_hooks/solana/useSolanaAccount'
    | '/_hooks/solana/useSolanaBalance'
    | '/_hooks/solana/useSwitchCluster'
    | '/_hooks/utils/useUI'
    | '/_hooks/wagmi/useAccount'
    | '/_hooks/wagmi/useBalance'
    | '/_hooks/wagmi/useDisconnect'
    | '/_hooks/wagmi/useSwitchChain'
    | '/_hooks/wallet/useSolanaEmbeddedWallet'
    | '/_hooks/wallet/useWalletAssets'
    | '/_hooks/wallet/useWallets'
    | '/_showcase/showcase/auth'
    | '/_showcase/showcase/auth/callback'
    | '/_showcase/showcase/auth/connect-wallet'
    | '/_showcase/showcase/auth/forgot-password'
    | '/_showcase/showcase/auth/login'
    | '/_showcase/showcase/auth/password-callback'
    | '/_showcase/showcase/auth/signup'
    | '/_showcase/showcase/auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HooksRoute: typeof HooksRouteWithChildren
  ShowcaseRoute: typeof ShowcaseRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_showcase': {
      id: '/_showcase'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hooks': {
      id: '/_hooks'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_showcase/': {
      id: '/_showcase/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShowcaseIndexRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/_hooks/wagmi': {
      id: '/_hooks/wagmi'
      path: '/wagmi'
      fullPath: '/wagmi'
      preLoaderRoute: typeof HooksWagmiRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_hooks/solana': {
      id: '/_hooks/solana'
      path: '/solana'
      fullPath: '/solana'
      preLoaderRoute: typeof HooksSolanaRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_hooks/provider': {
      id: '/_hooks/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof HooksProviderRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_hooks/adapter': {
      id: '/_hooks/adapter'
      path: '/adapter'
      fullPath: '/adapter'
      preLoaderRoute: typeof HooksAdapterRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_showcase/showcase/auth': {
      id: '/_showcase/showcase/auth'
      path: '/showcase/auth'
      fullPath: '/showcase/auth'
      preLoaderRoute: typeof ShowcaseShowcaseAuthRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/_hooks/wallet/useWallets': {
      id: '/_hooks/wallet/useWallets'
      path: '/wallet/useWallets'
      fullPath: '/wallet/useWallets'
      preLoaderRoute: typeof HooksWalletUseWalletsRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_hooks/wallet/useWalletAssets': {
      id: '/_hooks/wallet/useWalletAssets'
      path: '/wallet/useWalletAssets'
      fullPath: '/wallet/useWalletAssets'
      preLoaderRoute: typeof HooksWalletUseWalletAssetsRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_hooks/wallet/useSolanaEmbeddedWallet': {
      id: '/_hooks/wallet/useSolanaEmbeddedWallet'
      path: '/wallet/useSolanaEmbeddedWallet'
      fullPath: '/wallet/useSolanaEmbeddedWallet'
      preLoaderRoute: typeof HooksWalletUseSolanaEmbeddedWalletRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_hooks/wagmi/useSwitchChain': {
      id: '/_hooks/wagmi/useSwitchChain'
      path: '/useSwitchChain'
      fullPath: '/wagmi/useSwitchChain'
      preLoaderRoute: typeof HooksWagmiUseSwitchChainRouteImport
      parentRoute: typeof HooksWagmiRoute
    }
    '/_hooks/wagmi/useDisconnect': {
      id: '/_hooks/wagmi/useDisconnect'
      path: '/useDisconnect'
      fullPath: '/wagmi/useDisconnect'
      preLoaderRoute: typeof HooksWagmiUseDisconnectRouteImport
      parentRoute: typeof HooksWagmiRoute
    }
    '/_hooks/wagmi/useBalance': {
      id: '/_hooks/wagmi/useBalance'
      path: '/useBalance'
      fullPath: '/wagmi/useBalance'
      preLoaderRoute: typeof HooksWagmiUseBalanceRouteImport
      parentRoute: typeof HooksWagmiRoute
    }
    '/_hooks/wagmi/useAccount': {
      id: '/_hooks/wagmi/useAccount'
      path: '/useAccount'
      fullPath: '/wagmi/useAccount'
      preLoaderRoute: typeof HooksWagmiUseAccountRouteImport
      parentRoute: typeof HooksWagmiRoute
    }
    '/_hooks/utils/useUI': {
      id: '/_hooks/utils/useUI'
      path: '/utils/useUI'
      fullPath: '/utils/useUI'
      preLoaderRoute: typeof HooksUtilsUseUIRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_hooks/solana/useSwitchCluster': {
      id: '/_hooks/solana/useSwitchCluster'
      path: '/useSwitchCluster'
      fullPath: '/solana/useSwitchCluster'
      preLoaderRoute: typeof HooksSolanaUseSwitchClusterRouteImport
      parentRoute: typeof HooksSolanaRoute
    }
    '/_hooks/solana/useSolanaBalance': {
      id: '/_hooks/solana/useSolanaBalance'
      path: '/useSolanaBalance'
      fullPath: '/solana/useSolanaBalance'
      preLoaderRoute: typeof HooksSolanaUseSolanaBalanceRouteImport
      parentRoute: typeof HooksSolanaRoute
    }
    '/_hooks/solana/useSolanaAccount': {
      id: '/_hooks/solana/useSolanaAccount'
      path: '/useSolanaAccount'
      fullPath: '/solana/useSolanaAccount'
      preLoaderRoute: typeof HooksSolanaUseSolanaAccountRouteImport
      parentRoute: typeof HooksSolanaRoute
    }
    '/_hooks/solana/useDisconnect': {
      id: '/_hooks/solana/useDisconnect'
      path: '/useDisconnect'
      fullPath: '/solana/useDisconnect'
      preLoaderRoute: typeof HooksSolanaUseDisconnectRouteImport
      parentRoute: typeof HooksSolanaRoute
    }
    '/_hooks/auth/useWalletAuth': {
      id: '/_hooks/auth/useWalletAuth'
      path: '/auth/useWalletAuth'
      fullPath: '/auth/useWalletAuth'
      preLoaderRoute: typeof HooksAuthUseWalletAuthRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_hooks/auth/useUser': {
      id: '/_hooks/auth/useUser'
      path: '/auth/useUser'
      fullPath: '/auth/useUser'
      preLoaderRoute: typeof HooksAuthUseUserRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_hooks/auth/useSignOut': {
      id: '/_hooks/auth/useSignOut'
      path: '/auth/useSignOut'
      fullPath: '/auth/useSignOut'
      preLoaderRoute: typeof HooksAuthUseSignOutRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_hooks/auth/useOauth': {
      id: '/_hooks/auth/useOauth'
      path: '/auth/useOauth'
      fullPath: '/auth/useOauth'
      preLoaderRoute: typeof HooksAuthUseOauthRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_hooks/auth/useGuestAuth': {
      id: '/_hooks/auth/useGuestAuth'
      path: '/auth/useGuestAuth'
      fullPath: '/auth/useGuestAuth'
      preLoaderRoute: typeof HooksAuthUseGuestAuthRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_hooks/auth/useEmailAuth': {
      id: '/_hooks/auth/useEmailAuth'
      path: '/auth/useEmailAuth'
      fullPath: '/auth/useEmailAuth'
      preLoaderRoute: typeof HooksAuthUseEmailAuthRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_hooks/auth/useAuthCallback': {
      id: '/_hooks/auth/useAuthCallback'
      path: '/auth/useAuthCallback'
      fullPath: '/auth/useAuthCallback'
      preLoaderRoute: typeof HooksAuthUseAuthCallbackRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_hooks/adapter/useSwitchChain': {
      id: '/_hooks/adapter/useSwitchChain'
      path: '/useSwitchChain'
      fullPath: '/adapter/useSwitchChain'
      preLoaderRoute: typeof HooksAdapterUseSwitchChainRouteImport
      parentRoute: typeof HooksAdapterRoute
    }
    '/_hooks/adapter/useDisconnect': {
      id: '/_hooks/adapter/useDisconnect'
      path: '/useDisconnect'
      fullPath: '/adapter/useDisconnect'
      preLoaderRoute: typeof HooksAdapterUseDisconnectRouteImport
      parentRoute: typeof HooksAdapterRoute
    }
    '/_hooks/adapter/useBalance': {
      id: '/_hooks/adapter/useBalance'
      path: '/useBalance'
      fullPath: '/adapter/useBalance'
      preLoaderRoute: typeof HooksAdapterUseBalanceRouteImport
      parentRoute: typeof HooksAdapterRoute
    }
    '/_hooks/adapter/useAccount': {
      id: '/_hooks/adapter/useAccount'
      path: '/useAccount'
      fullPath: '/adapter/useAccount'
      preLoaderRoute: typeof HooksAdapterUseAccountRouteImport
      parentRoute: typeof HooksAdapterRoute
    }
    '/_showcase/showcase/auth/': {
      id: '/_showcase/showcase/auth/'
      path: '/'
      fullPath: '/showcase/auth/'
      preLoaderRoute: typeof ShowcaseShowcaseAuthIndexRouteImport
      parentRoute: typeof ShowcaseShowcaseAuthRoute
    }
    '/_showcase/showcase/auth/signup': {
      id: '/_showcase/showcase/auth/signup'
      path: '/signup'
      fullPath: '/showcase/auth/signup'
      preLoaderRoute: typeof ShowcaseShowcaseAuthSignupRouteImport
      parentRoute: typeof ShowcaseShowcaseAuthRoute
    }
    '/_showcase/showcase/auth/password-callback': {
      id: '/_showcase/showcase/auth/password-callback'
      path: '/password-callback'
      fullPath: '/showcase/auth/password-callback'
      preLoaderRoute: typeof ShowcaseShowcaseAuthPasswordCallbackRouteImport
      parentRoute: typeof ShowcaseShowcaseAuthRoute
    }
    '/_showcase/showcase/auth/login': {
      id: '/_showcase/showcase/auth/login'
      path: '/login'
      fullPath: '/showcase/auth/login'
      preLoaderRoute: typeof ShowcaseShowcaseAuthLoginRouteImport
      parentRoute: typeof ShowcaseShowcaseAuthRoute
    }
    '/_showcase/showcase/auth/forgot-password': {
      id: '/_showcase/showcase/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/showcase/auth/forgot-password'
      preLoaderRoute: typeof ShowcaseShowcaseAuthForgotPasswordRouteImport
      parentRoute: typeof ShowcaseShowcaseAuthRoute
    }
    '/_showcase/showcase/auth/connect-wallet': {
      id: '/_showcase/showcase/auth/connect-wallet'
      path: '/connect-wallet'
      fullPath: '/showcase/auth/connect-wallet'
      preLoaderRoute: typeof ShowcaseShowcaseAuthConnectWalletRouteImport
      parentRoute: typeof ShowcaseShowcaseAuthRoute
    }
    '/_showcase/showcase/auth/callback': {
      id: '/_showcase/showcase/auth/callback'
      path: '/callback'
      fullPath: '/showcase/auth/callback'
      preLoaderRoute: typeof ShowcaseShowcaseAuthCallbackRouteImport
      parentRoute: typeof ShowcaseShowcaseAuthRoute
    }
  }
}

interface HooksAdapterRouteChildren {
  HooksAdapterUseAccountRoute: typeof HooksAdapterUseAccountRoute
  HooksAdapterUseBalanceRoute: typeof HooksAdapterUseBalanceRoute
  HooksAdapterUseDisconnectRoute: typeof HooksAdapterUseDisconnectRoute
  HooksAdapterUseSwitchChainRoute: typeof HooksAdapterUseSwitchChainRoute
}

const HooksAdapterRouteChildren: HooksAdapterRouteChildren = {
  HooksAdapterUseAccountRoute: HooksAdapterUseAccountRoute,
  HooksAdapterUseBalanceRoute: HooksAdapterUseBalanceRoute,
  HooksAdapterUseDisconnectRoute: HooksAdapterUseDisconnectRoute,
  HooksAdapterUseSwitchChainRoute: HooksAdapterUseSwitchChainRoute,
}

const HooksAdapterRouteWithChildren = HooksAdapterRoute._addFileChildren(
  HooksAdapterRouteChildren,
)

interface HooksSolanaRouteChildren {
  HooksSolanaUseDisconnectRoute: typeof HooksSolanaUseDisconnectRoute
  HooksSolanaUseSolanaAccountRoute: typeof HooksSolanaUseSolanaAccountRoute
  HooksSolanaUseSolanaBalanceRoute: typeof HooksSolanaUseSolanaBalanceRoute
  HooksSolanaUseSwitchClusterRoute: typeof HooksSolanaUseSwitchClusterRoute
}

const HooksSolanaRouteChildren: HooksSolanaRouteChildren = {
  HooksSolanaUseDisconnectRoute: HooksSolanaUseDisconnectRoute,
  HooksSolanaUseSolanaAccountRoute: HooksSolanaUseSolanaAccountRoute,
  HooksSolanaUseSolanaBalanceRoute: HooksSolanaUseSolanaBalanceRoute,
  HooksSolanaUseSwitchClusterRoute: HooksSolanaUseSwitchClusterRoute,
}

const HooksSolanaRouteWithChildren = HooksSolanaRoute._addFileChildren(
  HooksSolanaRouteChildren,
)

interface HooksWagmiRouteChildren {
  HooksWagmiUseAccountRoute: typeof HooksWagmiUseAccountRoute
  HooksWagmiUseBalanceRoute: typeof HooksWagmiUseBalanceRoute
  HooksWagmiUseDisconnectRoute: typeof HooksWagmiUseDisconnectRoute
  HooksWagmiUseSwitchChainRoute: typeof HooksWagmiUseSwitchChainRoute
}

const HooksWagmiRouteChildren: HooksWagmiRouteChildren = {
  HooksWagmiUseAccountRoute: HooksWagmiUseAccountRoute,
  HooksWagmiUseBalanceRoute: HooksWagmiUseBalanceRoute,
  HooksWagmiUseDisconnectRoute: HooksWagmiUseDisconnectRoute,
  HooksWagmiUseSwitchChainRoute: HooksWagmiUseSwitchChainRoute,
}

const HooksWagmiRouteWithChildren = HooksWagmiRoute._addFileChildren(
  HooksWagmiRouteChildren,
)

interface HooksRouteChildren {
  HooksAdapterRoute: typeof HooksAdapterRouteWithChildren
  HooksProviderRoute: typeof HooksProviderRoute
  HooksSolanaRoute: typeof HooksSolanaRouteWithChildren
  HooksWagmiRoute: typeof HooksWagmiRouteWithChildren
  HooksAuthUseAuthCallbackRoute: typeof HooksAuthUseAuthCallbackRoute
  HooksAuthUseEmailAuthRoute: typeof HooksAuthUseEmailAuthRoute
  HooksAuthUseGuestAuthRoute: typeof HooksAuthUseGuestAuthRoute
  HooksAuthUseOauthRoute: typeof HooksAuthUseOauthRoute
  HooksAuthUseSignOutRoute: typeof HooksAuthUseSignOutRoute
  HooksAuthUseUserRoute: typeof HooksAuthUseUserRoute
  HooksAuthUseWalletAuthRoute: typeof HooksAuthUseWalletAuthRoute
  HooksUtilsUseUIRoute: typeof HooksUtilsUseUIRoute
  HooksWalletUseSolanaEmbeddedWalletRoute: typeof HooksWalletUseSolanaEmbeddedWalletRoute
  HooksWalletUseWalletAssetsRoute: typeof HooksWalletUseWalletAssetsRoute
  HooksWalletUseWalletsRoute: typeof HooksWalletUseWalletsRoute
}

const HooksRouteChildren: HooksRouteChildren = {
  HooksAdapterRoute: HooksAdapterRouteWithChildren,
  HooksProviderRoute: HooksProviderRoute,
  HooksSolanaRoute: HooksSolanaRouteWithChildren,
  HooksWagmiRoute: HooksWagmiRouteWithChildren,
  HooksAuthUseAuthCallbackRoute: HooksAuthUseAuthCallbackRoute,
  HooksAuthUseEmailAuthRoute: HooksAuthUseEmailAuthRoute,
  HooksAuthUseGuestAuthRoute: HooksAuthUseGuestAuthRoute,
  HooksAuthUseOauthRoute: HooksAuthUseOauthRoute,
  HooksAuthUseSignOutRoute: HooksAuthUseSignOutRoute,
  HooksAuthUseUserRoute: HooksAuthUseUserRoute,
  HooksAuthUseWalletAuthRoute: HooksAuthUseWalletAuthRoute,
  HooksUtilsUseUIRoute: HooksUtilsUseUIRoute,
  HooksWalletUseSolanaEmbeddedWalletRoute:
    HooksWalletUseSolanaEmbeddedWalletRoute,
  HooksWalletUseWalletAssetsRoute: HooksWalletUseWalletAssetsRoute,
  HooksWalletUseWalletsRoute: HooksWalletUseWalletsRoute,
}

const HooksRouteWithChildren = HooksRoute._addFileChildren(HooksRouteChildren)

interface ShowcaseShowcaseAuthRouteChildren {
  ShowcaseShowcaseAuthCallbackRoute: typeof ShowcaseShowcaseAuthCallbackRoute
  ShowcaseShowcaseAuthConnectWalletRoute: typeof ShowcaseShowcaseAuthConnectWalletRoute
  ShowcaseShowcaseAuthForgotPasswordRoute: typeof ShowcaseShowcaseAuthForgotPasswordRoute
  ShowcaseShowcaseAuthLoginRoute: typeof ShowcaseShowcaseAuthLoginRoute
  ShowcaseShowcaseAuthPasswordCallbackRoute: typeof ShowcaseShowcaseAuthPasswordCallbackRoute
  ShowcaseShowcaseAuthSignupRoute: typeof ShowcaseShowcaseAuthSignupRoute
  ShowcaseShowcaseAuthIndexRoute: typeof ShowcaseShowcaseAuthIndexRoute
}

const ShowcaseShowcaseAuthRouteChildren: ShowcaseShowcaseAuthRouteChildren = {
  ShowcaseShowcaseAuthCallbackRoute: ShowcaseShowcaseAuthCallbackRoute,
  ShowcaseShowcaseAuthConnectWalletRoute:
    ShowcaseShowcaseAuthConnectWalletRoute,
  ShowcaseShowcaseAuthForgotPasswordRoute:
    ShowcaseShowcaseAuthForgotPasswordRoute,
  ShowcaseShowcaseAuthLoginRoute: ShowcaseShowcaseAuthLoginRoute,
  ShowcaseShowcaseAuthPasswordCallbackRoute:
    ShowcaseShowcaseAuthPasswordCallbackRoute,
  ShowcaseShowcaseAuthSignupRoute: ShowcaseShowcaseAuthSignupRoute,
  ShowcaseShowcaseAuthIndexRoute: ShowcaseShowcaseAuthIndexRoute,
}

const ShowcaseShowcaseAuthRouteWithChildren =
  ShowcaseShowcaseAuthRoute._addFileChildren(ShowcaseShowcaseAuthRouteChildren)

interface ShowcaseRouteChildren {
  ShowcaseIndexRoute: typeof ShowcaseIndexRoute
  ShowcaseShowcaseAuthRoute: typeof ShowcaseShowcaseAuthRouteWithChildren
}

const ShowcaseRouteChildren: ShowcaseRouteChildren = {
  ShowcaseIndexRoute: ShowcaseIndexRoute,
  ShowcaseShowcaseAuthRoute: ShowcaseShowcaseAuthRouteWithChildren,
}

const ShowcaseRouteWithChildren = ShowcaseRoute._addFileChildren(
  ShowcaseRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  HooksRoute: HooksRouteWithChildren,
  ShowcaseRoute: ShowcaseRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
